var htmlBody = "";
var data1 = [{title: "Google GSuite", subtitle: "This set of activities will help you interact with Google Calendar, Drive, Sheets, and Gmail", url:"https://go.uipath.com/component/google-gsuite", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Activity Creator", subtitle: "A Visual Studio extension that creates custom activities for you in minutes", url:"https://go.uipath.com/component/activity-set-creator", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12664/transformed_transformed_transformed_ic_solution.png?v=1547911001", type: "Solution"}, 
{title: "Personal Interactive Assistant", subtitle: "An attended automation framework that enhances the interaction between the user and the robot", url:"https://go.uipath.com/component/personal-interactive-framework", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12660/transformed_transformed_transformed_ic_workflow_template.png?v=1547911054", type: "Workflow template"}, 
{title: "ABBYY - FlexiCapture Connector", subtitle: "ABBYY FlexiCapture Connector enables UiPath robot designers to connect ABBYY FlexiCapture Distributed into a robotic process flow", url:"https://go.uipath.com/component/abbyy-flexicapture-connector-for-uipath-31cc20", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}, 
{title: "Microsoft Office 365", subtitle: "Productivity just got easier with robots that can now collaborate using Microsoft Office 365 Activities for Excel Online, Outlook and, OneDrive", url:"https://go.uipath.com/component/microsoft-office-365-669054", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "UiPath Face Recognition Framework", subtitle: "The recognition is completely based on deep learning neural network and implanted using Tensorflow framework", url:"https://go.uipath.com/component/uipath-face-recognition-framework-51c6f7", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12663/transformed_transformed_transformed_ic_machine_learning_model.png?v=1547910986", type: "Machine learning model"}, 
{title: "Split Address", subtitle: "This snippet splits an address contained in a single string and creates pairs based on key words", url:"https://go.uipath.com/component/split-address", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12665/transformed_transformed_transformed_ic_snippet.png?v=1547911070", type: "Snippet"},
{title: "Generic Kibana Dashboard", subtitle: "This is a generic dashboard that provide details like AHT, bot and process relation, etc. using the default logs generated in Kibana with the default index (eg : Robot name, etc)", url:"https://go.uipath.com/component/generic_kibana_dashboard-104d35", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12661/transformed_transformed_transformed_ic_dashboard.png?v=1547911019", type: "Dashboard"},
{title: "AI-OCR Workflow for Fast Accounting", subtitle: "Workflow to easily invoke AI-OCR service of Fast Accounting via Web API", url:"https://go.uipath.com/component/ai-ocr-workflow-for-fast-accounting", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}];

var data2 = [{title: "Connector for Salesforce Lightning Platform", subtitle: "A set of 100 Activities and 5 wizards that allow you to do a very fast implementation for Salesforce Lightning Platform", url:"https://go.uipath.com/component/connector-for-salesforce-lightning-platform", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Clothing Consultant - Robot Pack", subtitle: "This simple robot will show you the forecast and suggest clothing that’s appropriate for the day’s weather", url:"https://go.uipath.com/component/clothing-consultant-robot-pack", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12660/transformed_transformed_transformed_ic_workflow_template.png?v=1547911054", type: "Workflow template"}, 
{title: "Public Records Request", subtitle: "Public Sector solution that takes user input and searches data repositories for matching data sets", url:"https://go.uipath.com/component/public-records-request-7dbdba", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12664/transformed_transformed_transformed_ic_solution.png?v=1547911001", type: "Solution"}, 
{title: "Orchestrator Smart Scheduler", subtitle: "Node.js app that will be able to start jobs or add queue items when some specific events occur", url:"https://go.uipath.com/component/orchestrator-smart-scheduler", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}, 
{title: "REFramework as library", subtitle: "Classic Robotic Enterprise Framework implemented as custom activity", url:"https://go.uipath.com/component/reframework-as-library", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Sentiment Analysis ML Model - on premise", subtitle: "This ML Model analyzes text fragments and returns a sentiment prediction between 0 and 1, where 0 is extremely negative and 1 is extremely positive", url:"https://go.uipath.com/component/sentiment-analysis-ml-model-on-premise", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12663/transformed_transformed_transformed_ic_machine_learning_model.png?v=1547910986", type: "Machine learning model"}, 
{title: "Kibana Jobs, Errors, and Queues Dashboards", subtitle: "Interactive Kibana dashboards for jobs, errors, and queue processes, using data from robot logs pushed to Elasticsearch", url:"https://go.uipath.com/component/kibana-jobs-errors-and-queues-dashboards", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12661/transformed_transformed_transformed_ic_dashboard.png?v=1547911019", type: "Dashboard"},
{title: "Kill Processes per User", subtitle: "Hard kill from a list of process names to clean Windows environment of open applications for the active user / robot", url:"https://go.uipath.com/component/killprocessesperuser", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12665/transformed_transformed_transformed_ic_snippet.png?v=1547911070", type: "Snippet"},
{title: "Jenkins Plugin for UiPath - Public Preview", subtitle: "CI/CD pipelining for UiPath automation processes in Jenkins", url:"https://go.uipath.com/component/jenkins-plugin-for-uipath-public-preview", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}];

var data3 = [{title: "IBM Watson Empathy Pack", subtitle: "Harness the brilliance of IBM Watson to give your robots a more human side", url:"https://go.uipath.com/component/ibm-watson-empathy-pack-950c8a", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Alpaca Form Builder", subtitle: "This library and project template allows UiPath Studio users to build rich HTML forms with a variety of UI controls and configurable validation", url:"https://go.uipath.com/component/alpaca-uipath-form-builder", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12664/transformed_transformed_transformed_ic_solution.png?v=1547911001", type: "Solution"}, 
{title: "Testing Framework for UiPath", subtitle: "Tired of testing workflows manually? This framework for running unit tests will help ease the development and save time", url:"https://go.uipath.com/component/uipath-testing-framework", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12660/transformed_transformed_transformed_ic_workflow_template.png?v=1547911054", type: "Workflow template"}, 
{title: "Update Robot Password in Orchestrator", subtitle: "PowerShell script to update the password of a provisioned Robot on Orchestrator", url:"https://go.uipath.com/component/update-robot-password-on-orchestrator", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}, 
{title: "IBM Watson Text Translator", subtitle: "Watson is now your personal interpreter", url:"https://go.uipath.com/component/ibm-watson-text-translator", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Templateless Receipt Extraction ML model - cloud", subtitle: "This Machine Learning model extracts Business name and address, Total amount and Date from receipt images", url:"https://go.uipath.com/component/templateless-receipt-extraction-ml-model-cloud", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12663/transformed_transformed_transformed_ic_machine_learning_model.png?v=1547910986", type: "Machine learning model"}, 
{title: "Generate Dates Range", subtitle: "This component will generate a list of dates for a given scope.", url:"https://go.uipath.com/component/generate-dates-range", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12665/transformed_transformed_transformed_ic_snippet.png?v=1547911070", type: "Snippet"},
{title: "Power BI Jobs and Queues Dashboards", subtitle: "Interactive Power BI dashboards on the topic of jobs and queues processes, using data from the Orchestrator SQL Server database", url:"https://go.uipath.com/component/power-bi-jobs-and-queues-dashboards", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12661/transformed_transformed_transformed_ic_dashboard.png?v=1547911019", type: "Dashboard"},
{title: "Orchestrator for Node-RED", subtitle: "Orchestrator in overdrive. Webhooks, Custom UIs, IoT. Node-RED is the bridge that connects UiPath to the digital world over", url:"https://go.uipath.com/component/orchestrator-for-node-red-583833", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}];

var data4 = [{title: "Excel Extension Activities", subtitle: "This Activity library allows easy integration with Excel. The Activities will mimic human actions. It also works with large excel files", url:"https://go.uipath.com/component/excel-extension-activities", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Robot Streaming", subtitle: "This tool allows you to stream the work of an unattended/attended robot to any other machine in same domain/network", url:"https://go.uipath.com/component/robot-streaming", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12664/transformed_transformed_transformed_ic_solution.png?v=1547911001", type: "Solution"}, 
{title: "Enhanced REFrameWork", subtitle: "A UiPath Studio template upon which you can build, test and run attended and unattended business processes, irrespective of process data types and process linearity", url:"https://go.uipath.com/component/enhanced-reframework-57011", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12660/transformed_transformed_transformed_ic_workflow_template.png?v=1547911054", type: "Workflow template"}, 
{title: "Chatbot with Dialog flow", subtitle: "Sample integration with Dialog flow to create an RPA-enabled chatbot", url:"https://go.uipath.com/component/chatbot-with-dialogflow-ai", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}, 
{title: "DocuSign Activity Pack for UiPath", subtitle: "Bringing Electronic Signing into the RPA world", url:"https://go.uipath.com/component/docusign-activity-pack-for-uipath", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Intelligent Ticket Classifier - CLASSie", subtitle: "Intelligent email classification model, categorizing to a predefined set of ticket classes or work queues", url:"https://go.uipath.com/component/classie-ticket-classifier", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12663/transformed_transformed_transformed_ic_machine_learning_model.png?v=1547910986", type: "Machine learning model"}, 
{title: "Visible Rows Counter for SAP Solutions", subtitle: "Reusable workflow for counting the number of rows visible on screen inside an SAP table", url:"https://go.uipath.com/component/table-visible-rows-counter-for-sap", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12665/transformed_transformed_transformed_ic_snippet.png?v=1547911070", type: "Snippet"},
{title: "Generic Kibana Dashboard", subtitle: "This is a generic dashboard that provide details like AHT, bot and process relation, etc. using the default logs generated in Kibana with the default index (eg : Robot name, etc)", url:"https://go.uipath.com/component/generic_kibana_dashboard-104d35", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12661/transformed_transformed_transformed_ic_dashboard.png?v=1547911019", type: "Dashboard"},
{title: "AI-OCR Workflow for Fast Accounting", subtitle: "Workflow to easily invoke AI-OCR service of Fast Accounting via Web API", url:"https://go.uipath.com/component/ai-ocr-workflow-for-fast-accounting", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}];

var data5 = [{title: "Extended App Integration for PDF", subtitle: "Extended PDF activities using the PDFSharp library", url:"https://go.uipath.com/component/extended-app-integration-for-pdf", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "Investigator - The Monitoring Tool", subtitle: "Monitor and manage all your robot related configurations from one place", url:"https://go.uipath.com/component/investigator", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12664/transformed_transformed_transformed_ic_solution.png?v=1547911001", type: "Solution"}, 
{title: "Enhanced REFrameWork", subtitle: "A UiPath Studio template upon which you can build, test and run attended and unattended business processes, irrespective of process data types and process linearity", url:"https://go.uipath.com/component/enhanced-reframework-57011", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12660/transformed_transformed_transformed_ic_workflow_template.png?v=1547911054", type: "Workflow template"}, 
{title: "Dropbox App Connector for UiPath", subtitle: "A custom Dropbox app connector for UiPath which is already used in custom UiPath Dropbox activities", url:"https://go.uipath.com/component/dropbox-app-connector-for-uipath", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}, 
{title: "Expert System", subtitle: "The Expert System package provides natural language understanding functionalities", url:"https://go.uipath.com/component/client-for-expert-system-f3d6a8", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12659/transformed_transformed_transformed_ic_custom_activity.png?v=1547911657", type: "Custom activity"}, 
{title: "UiPath Face Recognition Framework", subtitle: "The recognition is completely based on deep learning neural network and implanted using Tensorflow framework", url:"https://go.uipath.com/component/uipath-face-recognition-framework-51c6f7", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12663/transformed_transformed_transformed_ic_machine_learning_model.png?v=1547910986", type: "Machine learning model"}, 
{title: "Split Address", subtitle: "This snippet splits an address contained in a single string and creates pairs based on key words", url:"https://go.uipath.com/component/split-address", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12665/transformed_transformed_transformed_ic_snippet.png?v=1547911070", type: "Snippet"},
{title: "Tableau RPA Log Dashboard", subtitle: "Dashboards supporting business decisions on Robots logs", url:"https://go.uipath.com/component/savvy-insights", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12661/transformed_transformed_transformed_ic_dashboard.png?v=1547911019", type: "Dashboard"},
{title: "Upwire - Communication Workflow", subtitle: "Communications workflow drag & drop tool: SMS, Voice, Email & micro-forms used to extend RPA with data capture or external RPA initiation", url:"https://go.uipath.com/component/upwire-workflow", image: "https://dmtyylqvwgyxw.cloudfront.net/instances/214/uploads/images/custom_image/image/12662/transformed_transformed_transformed_ic_connector.png?v=1547911036", type: "Connector"}];

page = 1;
$('#1').addClass('active');
uploadData(data1);

function uploadData(data) {
    var count = 0;
    var htmlBody = "";
    for(var i in data) {
        count ++;
        if(count % 3 == 0)
            htmlBody += '<div class="row">';
        htmlBody += '<div class="col-md-4 catalog-item"><a href="#"><img class="img-responsive" width="20%" height="20%" src="' + data[i].image + '" alt="' + data[i].type + '"></a><h3><a href="#">';
        htmlBody += '<h3><a href="'+ data[i].url+'">'+ data[i].title +'</a></h3>';
        htmlBody += '<p style="font-weight: 50">'+ data[i].subtitle +'</p>';
        if(count % 3 == 0)
            htmlBody += '</div>';
        htmlBody += '</div>';
    }
    $('#catalog-body').html(htmlBody);
}

function pagination(x) {
    $('#' + page).removeClass('active');
    if (x === 'next' && page<5)
        page = page + 1;
    if (x === 'prev' && page>1)
        page = page - 1;
    if (x > 0 && x < 6)
        page = x;
    if (page == 5 && x == 'next')
        $("#btnNext").attr("disabled", true);
    else 
        $("#btnNext").attr("disabled", false);
        mapData = {
        1 : data1,
        2 : data2,
        3 : data3,
        4 : data4,
        5 : data5
    };
    $('#' + page).addClass('active');
    uploadData(mapData[page]);
}

